import type { Cafe } from "./types";

const workcafeImages = [
  "/workcafes/cafe-quiet-corner.png",
  "/workcafes/cafe-shared-table.png",
  "/workcafes/cafe-window-seat.png",
  "/workcafes/cafe-station-table.png",
];

const photo = (seed: string) => {
  const index = Array.from(seed).reduce(
    (total, character) => total + character.charCodeAt(0),
    0,
  );
  return workcafeImages[index % workcafeImages.length];
};

export const cafes: Cafe[] = [
  {
    id: "cafe_shoreditch_01",
    name: "Patch Table Shoreditch",
    area: "Shoreditch",
    address: "Redchurch Street, E2",
    lat: 51.5247,
    lng: -0.0752,
    rating: 4.6,
    reviewCount: 184,
    imageUrl: photo("shoreditch-table"),
    imageAlt: "Cafe table with laptop and coffee near a window",
    wifiScore: 5,
    plugScore: 4,
    seatingScore: 4,
    noiseLevel: "moderate",
    laptopFriendly: true,
    callFriendly: false,
    bestTime: "Morning to mid-afternoon",
    recommendedStay: "2-3 hours",
    bestFor: ["coding", "deep work", "good wifi"],
    workSummary:
      "Reliable WiFi, enough laptop seating, and a steady but not silent room.",
    foodHygieneRating: 5,
    source: "seed",
  },
  {
    id: "cafe_shoreditch_02",
    name: "Foundry Desk",
    area: "Shoreditch",
    address: "Great Eastern Street, EC2A",
    lat: 51.5256,
    lng: -0.0851,
    rating: 4.4,
    reviewCount: 97,
    imageUrl: photo("foundry-desk"),
    imageAlt: "Long cafe counter with stools and daylight",
    wifiScore: 4,
    plugScore: 5,
    seatingScore: 3,
    noiseLevel: "busy",
    laptopFriendly: true,
    callFriendly: false,
    bestTime: "Before lunch",
    recommendedStay: "1-2 hours",
    bestFor: ["plugs", "quick build sessions", "solo work"],
    workSummary:
      "Strong plug access, fast service, and best used before the lunch rush.",
    foodHygieneRating: 5,
    source: "seed",
  },
  {
    id: "cafe_liverpool_01",
    name: "Exchange Bench",
    area: "Liverpool Street",
    address: "Bishopsgate, EC2M",
    lat: 51.5186,
    lng: -0.0813,
    rating: 4.3,
    reviewCount: 213,
    imageUrl: photo("exchange-bench"),
    imageAlt: "Bright cafe seating with small tables",
    wifiScore: 5,
    plugScore: 4,
    seatingScore: 4,
    noiseLevel: "moderate",
    laptopFriendly: true,
    callFriendly: true,
    bestTime: "Late morning",
    recommendedStay: "2-3 hours",
    bestFor: ["calls", "finance district", "wifi"],
    workSummary:
      "A strong central choice with call-friendly corners and reliable WiFi.",
    foodHygieneRating: 4,
    source: "seed",
  },
  {
    id: "cafe_liverpool_02",
    name: "Broadgate Study",
    area: "Liverpool Street",
    address: "Sun Street Passage, EC2M",
    lat: 51.5201,
    lng: -0.0835,
    rating: 4.2,
    reviewCount: 128,
    imageUrl: photo("broadgate-study"),
    imageAlt: "Cafe window bar with stools and laptop space",
    wifiScore: 4,
    plugScore: 3,
    seatingScore: 5,
    noiseLevel: "quiet",
    laptopFriendly: true,
    callFriendly: true,
    bestTime: "Afternoon",
    recommendedStay: "2 hours",
    bestFor: ["quiet", "calls", "reading"],
    workSummary:
      "More seating than sockets, but calm enough for calls and planning work.",
    foodHygieneRating: 5,
    source: "seed",
  },
  {
    id: "cafe_kings_cross_01",
    name: "Coal Drops Workspace",
    area: "King's Cross",
    address: "Stable Street, N1C",
    lat: 51.5362,
    lng: -0.1258,
    rating: 4.5,
    reviewCount: 162,
    imageUrl: photo("coal-drops-workspace"),
    imageAlt: "Industrial cafe with warm lighting and shared tables",
    wifiScore: 5,
    plugScore: 3,
    seatingScore: 5,
    noiseLevel: "moderate",
    laptopFriendly: true,
    callFriendly: false,
    bestTime: "Mid-morning",
    recommendedStay: "3 hours",
    bestFor: ["train gap", "pitch work", "long table"],
    workSummary:
      "Great if you need a focused block before a train, with generous tables.",
    foodHygieneRating: 5,
    source: "seed",
  },
  {
    id: "cafe_kings_cross_02",
    name: "Platform House Coffee",
    area: "King's Cross",
    address: "Pancras Road, N1C",
    lat: 51.5328,
    lng: -0.1241,
    rating: 4.1,
    reviewCount: 88,
    imageUrl: photo("platform-house"),
    imageAlt: "Small cafe table beside a station concourse window",
    wifiScore: 3,
    plugScore: 3,
    seatingScore: 3,
    noiseLevel: "busy",
    laptopFriendly: true,
    callFriendly: false,
    bestTime: "Early morning",
    recommendedStay: "1 hour",
    bestFor: ["short sessions", "station access", "email"],
    workSummary:
      "Convenient for a short sprint, but too busy for deep afternoon work.",
    foodHygieneRating: 4,
    source: "seed",
  },
  {
    id: "cafe_soho_01",
    name: "Wardour Quiet Room",
    area: "Soho",
    address: "Wardour Street, W1F",
    lat: 51.5135,
    lng: -0.1354,
    rating: 4.7,
    reviewCount: 146,
    imageUrl: photo("wardour-quiet-room"),
    imageAlt: "Cafe banquette with laptop and notebook",
    wifiScore: 4,
    plugScore: 4,
    seatingScore: 4,
    noiseLevel: "quiet",
    laptopFriendly: true,
    callFriendly: true,
    bestTime: "Morning",
    recommendedStay: "2 hours",
    bestFor: ["quiet", "calls", "writing"],
    workSummary:
      "A rare calm Soho option with enough sockets for a planned session.",
    foodHygieneRating: 5,
    source: "seed",
  },
  {
    id: "cafe_soho_02",
    name: "Milk Bar Draft",
    area: "Soho",
    address: "Greek Street, W1D",
    lat: 51.5148,
    lng: -0.1311,
    rating: 4.5,
    reviewCount: 231,
    imageUrl: photo("milk-bar-draft"),
    imageAlt: "Coffee cups on a narrow table in a city cafe",
    wifiScore: 4,
    plugScore: 2,
    seatingScore: 3,
    noiseLevel: "busy",
    laptopFriendly: true,
    callFriendly: false,
    bestTime: "Before 11am",
    recommendedStay: "1 hour",
    bestFor: ["email", "quick edits", "central"],
    workSummary:
      "Good coffee and decent WiFi, but sockets are limited after breakfast.",
    foodHygieneRating: 5,
    source: "seed",
  },
  {
    id: "cafe_southbank_01",
    name: "Riverside Focus",
    area: "South Bank",
    address: "Belvedere Road, SE1",
    lat: 51.5067,
    lng: -0.1156,
    rating: 4.3,
    reviewCount: 119,
    imageUrl: photo("riverside-focus"),
    imageAlt: "Open cafe space with river-facing windows",
    wifiScore: 4,
    plugScore: 3,
    seatingScore: 5,
    noiseLevel: "moderate",
    laptopFriendly: true,
    callFriendly: false,
    bestTime: "Afternoon",
    recommendedStay: "2-3 hours",
    bestFor: ["writing", "views", "spacious seating"],
    workSummary:
      "Spacious and bright, better for writing than calls once footfall rises.",
    foodHygieneRating: 4,
    source: "seed",
  },
  {
    id: "cafe_waterloo_01",
    name: "Lower Marsh Desk",
    area: "Waterloo",
    address: "Lower Marsh, SE1",
    lat: 51.5009,
    lng: -0.1115,
    rating: 4.4,
    reviewCount: 102,
    imageUrl: photo("lower-marsh-desk"),
    imageAlt: "Small cafe with brick wall and laptop seating",
    wifiScore: 4,
    plugScore: 4,
    seatingScore: 4,
    noiseLevel: "moderate",
    laptopFriendly: true,
    callFriendly: true,
    bestTime: "Late morning",
    recommendedStay: "2 hours",
    bestFor: ["meetings", "train gap", "plugs"],
    workSummary:
      "A balanced Waterloo option with enough outlets and stable seating.",
    foodHygieneRating: 5,
    source: "seed",
  },
  {
    id: "cafe_notting_hill_01",
    name: "Portobello Pages",
    area: "Notting Hill",
    address: "Portobello Road, W11",
    lat: 51.5152,
    lng: -0.2045,
    rating: 4.6,
    reviewCount: 151,
    imageUrl: photo("portobello-pages"),
    imageAlt: "Neighbourhood cafe table with books and laptop",
    wifiScore: 4,
    plugScore: 3,
    seatingScore: 4,
    noiseLevel: "quiet",
    laptopFriendly: true,
    callFriendly: false,
    bestTime: "Weekday morning",
    recommendedStay: "2 hours",
    bestFor: ["reading", "writing", "quiet"],
    workSummary:
      "Calm on weekdays, with enough space for writing and research blocks.",
    foodHygieneRating: 5,
    source: "seed",
  },
  {
    id: "cafe_camden_01",
    name: "Canal Desk Camden",
    area: "Camden",
    address: "Camden High Street, NW1",
    lat: 51.5392,
    lng: -0.1426,
    rating: 4.2,
    reviewCount: 74,
    imageUrl: photo("canal-desk-camden"),
    imageAlt: "Cafe table near plants and a canal-side window",
    wifiScore: 3,
    plugScore: 4,
    seatingScore: 3,
    noiseLevel: "busy",
    laptopFriendly: true,
    callFriendly: false,
    bestTime: "Morning",
    recommendedStay: "1-2 hours",
    bestFor: ["plugs", "short coding", "north London"],
    workSummary:
      "Useful socket access, but the room gets active after lunch.",
    foodHygieneRating: 4,
    source: "seed",
  },
  {
    id: "cafe_clerkenwell_01",
    name: "Clerkenwell Common",
    area: "Clerkenwell",
    address: "St John Street, EC1M",
    lat: 51.5228,
    lng: -0.1024,
    rating: 4.7,
    reviewCount: 141,
    imageUrl: photo("clerkenwell-common"),
    imageAlt: "Cafe corner with daylight, laptop, and coffee",
    wifiScore: 5,
    plugScore: 5,
    seatingScore: 4,
    noiseLevel: "quiet",
    laptopFriendly: true,
    callFriendly: true,
    bestTime: "Any weekday before 4pm",
    recommendedStay: "3 hours",
    bestFor: ["deep work", "calls", "long sessions"],
    workSummary:
      "The strongest all-rounder for deep work, calls, sockets, and WiFi.",
    foodHygieneRating: 5,
    source: "seed",
  },
  {
    id: "cafe_hackney_01",
    name: "Mare Street Hours",
    area: "Hackney",
    address: "Mare Street, E8",
    lat: 51.5448,
    lng: -0.0554,
    rating: 4.4,
    reviewCount: 109,
    imageUrl: photo("mare-street-hours"),
    imageAlt: "Neighbourhood cafe with shared table and plants",
    wifiScore: 4,
    plugScore: 4,
    seatingScore: 5,
    noiseLevel: "moderate",
    laptopFriendly: true,
    callFriendly: false,
    bestTime: "Early afternoon",
    recommendedStay: "2-3 hours",
    bestFor: ["design work", "long table", "east London"],
    workSummary:
      "Good shared tables and steady noise, best for visual or build work.",
    foodHygieneRating: 5,
    source: "seed",
  },
  {
    id: "cafe_brixton_01",
    name: "Atlantic Road Notes",
    area: "Brixton",
    address: "Atlantic Road, SW9",
    lat: 51.4626,
    lng: -0.1124,
    rating: 4.5,
    reviewCount: 134,
    imageUrl: photo("atlantic-road-notes"),
    imageAlt: "Cafe seating with warm lamps and open notebooks",
    wifiScore: 4,
    plugScore: 3,
    seatingScore: 4,
    noiseLevel: "moderate",
    laptopFriendly: true,
    callFriendly: false,
    bestTime: "Morning",
    recommendedStay: "2 hours",
    bestFor: ["writing", "planning", "coffee"],
    workSummary:
      "Comfortable for writing and planning, with enough WiFi for cloud docs.",
    foodHygieneRating: 4,
    source: "seed",
  },
  {
    id: "cafe_greenwich_01",
    name: "Meridian Workroom",
    area: "Greenwich",
    address: "Greenwich Church Street, SE10",
    lat: 51.4811,
    lng: -0.0093,
    rating: 4.3,
    reviewCount: 82,
    imageUrl: photo("meridian-workroom"),
    imageAlt: "Quiet cafe corner with a laptop beside a window",
    wifiScore: 4,
    plugScore: 4,
    seatingScore: 3,
    noiseLevel: "quiet",
    laptopFriendly: true,
    callFriendly: true,
    bestTime: "Weekday afternoon",
    recommendedStay: "2 hours",
    bestFor: ["calls", "quiet", "south east London"],
    workSummary:
      "A quiet south east option with better call conditions than most cafes.",
    foodHygieneRating: 5,
    source: "seed",
  },
  {
    id: "cafe_victoria_01",
    name: "Victoria Sprint",
    area: "Victoria",
    address: "Buckingham Palace Road, SW1W",
    lat: 51.4952,
    lng: -0.1446,
    rating: 4.0,
    reviewCount: 91,
    imageUrl: photo("victoria-sprint"),
    imageAlt: "Compact cafe booth with laptop and espresso",
    wifiScore: 3,
    plugScore: 2,
    seatingScore: 3,
    noiseLevel: "busy",
    laptopFriendly: true,
    callFriendly: false,
    bestTime: "Before 10am",
    recommendedStay: "45-90 minutes",
    bestFor: ["email", "station access", "quick tasks"],
    workSummary:
      "Best for quick admin before travel, not a full focus block.",
    foodHygieneRating: 4,
    source: "seed",
  },
  {
    id: "cafe_bank_01",
    name: "Threadneedle Quiet",
    area: "Bank",
    address: "Threadneedle Street, EC2R",
    lat: 51.5142,
    lng: -0.0885,
    rating: 4.5,
    reviewCount: 118,
    imageUrl: photo("threadneedle-quiet"),
    imageAlt: "Polished cafe seating with laptop-friendly tables",
    wifiScore: 5,
    plugScore: 4,
    seatingScore: 4,
    noiseLevel: "quiet",
    laptopFriendly: true,
    callFriendly: true,
    bestTime: "Mid-morning",
    recommendedStay: "2 hours",
    bestFor: ["calls", "finance", "focused admin"],
    workSummary:
      "Quiet for the City, with strong WiFi and enough space for calls.",
    foodHygieneRating: 5,
    source: "seed",
  },
  {
    id: "cafe_farringdon_01",
    name: "Smithfield Draft",
    area: "Farringdon",
    address: "Cowcross Street, EC1M",
    lat: 51.5202,
    lng: -0.1059,
    rating: 4.6,
    reviewCount: 156,
    imageUrl: photo("smithfield-draft"),
    imageAlt: "Cafe work table with coffee and a phone",
    wifiScore: 5,
    plugScore: 4,
    seatingScore: 5,
    noiseLevel: "moderate",
    laptopFriendly: true,
    callFriendly: true,
    bestTime: "Late morning to afternoon",
    recommendedStay: "3 hours",
    bestFor: ["long sessions", "pair work", "plugs"],
    workSummary:
      "A high-confidence pick for long sessions around Farringdon.",
    foodHygieneRating: 5,
    source: "seed",
  },
  {
    id: "cafe_canary_01",
    name: "Docklands Focus Bar",
    area: "Canary Wharf",
    address: "Canada Square, E14",
    lat: 51.5049,
    lng: -0.0195,
    rating: 4.2,
    reviewCount: 77,
    imageUrl: photo("docklands-focus"),
    imageAlt: "Modern cafe counter with laptop seating and city light",
    wifiScore: 4,
    plugScore: 5,
    seatingScore: 4,
    noiseLevel: "moderate",
    laptopFriendly: true,
    callFriendly: true,
    bestTime: "Afternoon",
    recommendedStay: "2-3 hours",
    bestFor: ["plugs", "calls", "east business"],
    workSummary:
      "Strong sockets and call tolerance, with business-district reliability.",
    foodHygieneRating: 4,
    source: "seed",
  },
];

export const cafeAreas = Array.from(new Set(cafes.map((cafe) => cafe.area))).sort();

export function getCafeById(id: string) {
  return cafes.find((cafe) => cafe.id === id);
}
